name: main
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.0.3
  get_it: ^3.0.1
  graphql_flutter: ^2.1.0
  flutter_facebook_login: ^3.0.0
  sailor: ^0.5.0
  mobx: 0.3.8+1
  flutter_mobx: 0.3.3+1
  flutter_platform_widgets: ^0.20.1
  google_sign_in: ^4.0.7
  linkedin_auth: any
  plaid: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0
  image_picker: ^0.6.1+11
  merge_map: ^1.0.2
builders:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  mobx_codegen: ^0.3.9+1
  json_serializable: ^3.2.3
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - env/
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/ru.json

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: AirbnbCerealApp
      fonts:
        - asset: assets/fonts/AirbnbCereal-Black.ttf
        - asset: assets/fonts/AirbnbCereal-Bold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCereal-Book.ttf
        - asset: assets/fonts/AirbnbCereal-ExtraBold.ttf
        - asset: assets/fonts/AirbnbCereal-Light.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCereal-Medium.ttf
          weight: 500